name: Benchmark

on: [push, pull_request_target, workflow_dispatch]

jobs:
  benchmark:
    name: Performance check
    if: contains(toJSON(github.event.head_commit.message), 'Merge pull request ') == false
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            src/*.c
            src/*.h
            lib/c.h
            lib/c.c

      - name: Download dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y graphviz jq
          sudo apt-get install -q -y qemu-user
          sudo apt-get install -q -y build-essential
          sudo apt-get install -q -y gcc-arm-linux-gnueabihf

      - name: Measure execution time and memory use for bootstrapping
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          make all-bench CC=gcc
          make all-bench CC=clang
